version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: bank-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: bank-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/bank
      - JWT_SECRET=your_super_secret_key_here
      - JWT_EXPIRES_IN=1h
    depends_on:
      - mongo
    volumes:
      - ./backend:/app/backend

volumes:
  mongo-data:
