openapi: 3.0.0
info:
  title: Bank API
  version: 1.0.0
  description: API documentation for the Bank App

paths:
  /signup:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - phone
              properties:
                email:
                  type: string
                password:
                  type: string
                phone:
                  type: string
      responses:
        "200":
          description: User registered successfully
        "400":
          description: Invalid input or user exists
